// Regenerate PARENTS array for Clinica using REAL product ids from PRODUCTS.
// This replaces the broken synthetic-id PoC generated by _build_parents.py.
global.window = {};
require('./assets/js/data.js');
const fs = require('fs');

const ps = window.PRODUCTS.filter(p => p.brand === 'Clinica');

// Cluster by regex rules
const clusters = {};
for (const p of ps) {
  const n = p.name;
  let key = 'unmatched';
  if (/クリニカＡＤ.*ハブラシ/.test(n) && /超コンパクト/.test(n)) key = 'AD_brush_supercompact';
  else if (/クリニカＡＤ.*ハブラシ/.test(n) && /コンパクト/.test(n)) key = 'AD_brush_compact';
  else if (/クリニカＡＤ.*ハブラシ/.test(n) && /レギュラー/.test(n)) key = 'AD_brush_regular';
  else if (/クリニカＡＤ.*ハブラシ/.test(n)) key = 'AD_brush_other';
  else if (/クリニカＡＤ.*デンタルタフト/.test(n)) key = 'AD_tauft';
  else if (/クリニカＡＤ.*(デンタルフロス|フロス|スポンジ)/.test(n)) key = 'AD_floss';
  else if (/クリニカＡＤ.*デンタルリンス/.test(n)) key = 'AD_rinse';
  else if (/クリニカＡＤ.*ジェル/.test(n)) key = 'AD_gel';
  else if (/クリニカＡＤ/.test(n) && /ハミガキ/.test(n)) key = 'AD_paste';
  else if (/クリニカＡＤ/.test(n)) key = 'AD_paste_other';
  else if (/クリニカＰＲＯ.*ラバーヘッド/.test(n)) key = 'PRO_brush_rubber';
  else if (/クリニカＰＲＯ.*アラームハンドル/.test(n)) key = 'PRO_brush_alarm';
  else if (/クリニカＰＲＯ.*ハブラシ/.test(n)) key = 'PRO_brush_other';
  else if (/クリニカＰＲＯオールインワン/.test(n)) key = 'PRO_allinone';
  else if (/クリニカＰＲＯ.*ホワイト|クリニカＰＲＯ[ＷＷ]/.test(n)) key = 'PRO_white';
  else if (/クリニカＰＲＯ.*(ｐｌｕｓ|Plus|歯周バリア)/.test(n)) key = 'PRO_plus';
  else if (/クリニカＰＲＯ.*ハミガキ/.test(n)) key = 'PRO_paste';
  else if (/エナメルパール/.test(n)) key = 'enamelpearl';
  else if (/クリニカＫｉｄ|クリニカKid/i.test(n) && /(ジェル|ジエル)/.test(n)) key = 'kids_gel';
  else if (/クリニカＫｉｄ|クリニカKid/i.test(n) && /ハミガキ/.test(n)) key = 'kids_paste';
  else if (/クリニカＫｉｄ|クリニカKid/i.test(n) && /ハブラシ/.test(n)) key = 'kids_brush';
  else if (/クリニカＫｉｄ|クリニカKid/i.test(n) && /リンス/.test(n)) key = 'kids_rinse';
  else if (/クリニカＪｒ|クリニカJr/i.test(n) && /ハミガキ/.test(n)) key = 'jr_paste';
  else if (/クリニカＪｒ|クリニカJr/i.test(n) && /リンス/.test(n)) key = 'jr_rinse';
  else if (/クリニカハミガキ/.test(n)) key = 'standard';
  else if (/クイックウォッシュ|クイックウォツシュ/.test(n)) key = 'quickwash';
  else if (/トラベル/.test(n)) key = 'travel';
  else if (/フッ素メディカル/.test(n)) key = 'fluor';
  (clusters[key] = clusters[key] || []).push(p);
}

const TYPE_BY_KEY = {
  AD_brush_supercompact:'brush', AD_brush_compact:'brush', AD_brush_regular:'brush', AD_brush_other:'brush',
  AD_tauft:'tauft', AD_floss:'floss', AD_rinse:'rinse', AD_gel:'gel', AD_paste:'paste', AD_paste_other:'paste',
  PRO_brush_rubber:'brush', PRO_brush_alarm:'brush', PRO_brush_other:'brush',
  PRO_allinone:'paste', PRO_white:'paste', PRO_plus:'paste', PRO_paste:'paste',
  enamelpearl:'paste',
  kids_gel:'gel', kids_paste:'paste', kids_brush:'brush', kids_rinse:'rinse',
  jr_paste:'paste', jr_rinse:'rinse',
  standard:'paste', quickwash:'rinse', travel:'paste', fluor:'coating', unmatched:'other'
};

const flavorsList = ['クール','シトラス','ソフト','クリアミント','シトラスミント','フレッシュミント','フレッシュクリーンミント','リッチシトラスミント','リフレッシュミント','ペアーシトラスミント','クリアシトラス','プレミアムミント','フレッシュシトラスミント','ホワイトフローラルミント','いちご','グレープ','ペアー','ハーブミント','ホワイト','やさしいミント','マイルド','フレッシュ','プラス','オールインワン','低刺激'];

function extractAttrs(p, type) {
  let capacity = 'standard', flavor = 'standard', form = type;
  const u = p.unit || '';
  const n = p.name;
  if (type === 'brush') {
    let m = n.match(/([三四五六七八九])列/);
    if (m) capacity = m[1] + '列';
    if (/超コンパクト/.test(n)) flavor = '超コンパクト';
    else if (/コンパクト/.test(n)) flavor = 'コンパクト';
    else if (/レギュラー/.test(n)) flavor = 'レギュラー';
    else if (/アラームハンドル/.test(n)) flavor = 'アラームハンドル';
    else if (/ラバーヘッド/.test(n)) flavor = 'ラバーヘッド';
    else if (/0～2才|0～2歳/.test(n)) flavor = '0～2才用';
  } else if (type === 'floss') {
    capacity = 'standard'; flavor = 'デンタルフロス';
  } else if (type === 'tauft') {
    capacity = 'standard'; flavor = 'デンタルタフト';
  } else if (type === 'rinse') {
    let m = u.match(/(\d+)\s*ml/i);
    if (m) capacity = m[1] + 'ml';
    else { let m2 = n.match(/(\d+)\s*ml/i); if (m2) capacity = m2[1] + 'ml'; }
  } else if (type === 'gel' || type === 'paste' || type === 'coating') {
    let m = u.match(/(\d+)\s*g/i);
    if (m) capacity = m[1] + 'g';
    else { let m2 = n.match(/(\d+)\s*g/); if (m2) capacity = m2[1] + 'g'; }
    for (const f of flavorsList) { if (n.includes(f)) { flavor = f; break; } }
  } else {
    capacity = u || 'standard';
  }
  return { capacity, flavor, form };
}

const SUB_BY_FORM = { brush: 'hygiene', floss: 'hygiene', tauft: 'hygiene', rinse: 'quasidrug', gel: 'quasidrug', paste: 'quasidrug', coating: 'quasidrug', other: 'hygiene' };

const parents = [];
for (const [key, products] of Object.entries(clusters)) {
  const type = TYPE_BY_KEY[key] || 'other';
  const variants = products.map(p => {
    const a = extractAttrs(p, type);
    return {
      id: p.id,
      jan: p.jan || p.id,
      capacity: a.capacity,
      flavor: a.flavor,
      form: a.form,
      price: p.price || 0,
      moq: p.moq || 0,
      tag: p.tag || '',
      hue: p.hue || '#21463D'
    };
  });
  const head = variants[0];
  const parentId = key === 'unmatched' ? 'clinica_single_' + head.id.slice(-6) : 'clinica_' + key;
  parents.push({
    id: parentId,
    brand: 'Clinica',
    series: 'Clinica ' + key.replace(/_/g, ' '),
    category: 'health',
    sub: SUB_BY_FORM[head.form],
    defaultVariantId: head.id,
    variants
  });
}

parents.sort((a, b) => a.id.localeCompare(b.id));

function jsStr(s){ return JSON.stringify(s); }
function fmtV(vs) {
  return vs.map((v, i) => {
    const last = i === vs.length - 1;
    return [
      '    {',
      '      id: ' + jsStr(v.id) + ',',
      '      jan: ' + jsStr(v.jan) + ',',
      '      capacity: ' + jsStr(v.capacity) + ',',
      '      flavor: ' + jsStr(v.flavor) + ',',
      '      form: ' + jsStr(v.form) + ',',
      '      price: ' + (v.price | 0) + ',',
      '      moq: ' + (v.moq | 0) + ',',
      '      tag: ' + jsStr(v.tag) + ',',
      '      hue: ' + jsStr(v.hue),
      '    }' + (last ? '' : ',')
    ].join('\n');
  }).join('\n');
}
function fmtP(p) {
  return [
    '  {',
    '    id: ' + jsStr(p.id) + ',',
    '    brand: ' + jsStr(p.brand) + ',',
    '    series: ' + jsStr(p.series) + ',',
    '    category: ' + jsStr(p.category) + ',',
    '    sub: ' + jsStr(p.sub) + ',',
    '    defaultVariantId: ' + jsStr(p.defaultVariantId) + ',',
    '    variants: [',
    fmtV(p.variants),
    '    ]',
    '  }'
  ].join('\n');
}

const totalVariants = parents.reduce((s, p) => s + p.variants.length, 0);
const out =
  '/* =========================================================\n' +
  '   PARENTS regenerated from real PRODUCTS ids via _gen_clinica_parents.js\n' +
  '   ' + parents.length + ' parents / ' + totalVariants + ' variants (target 68 Clinica SKUs)\n' +
  '   ========================================================= */\n' +
  'const PARENTS = [\n' + parents.map(fmtP).join(',\n') + '\n];\n' +
  'window.PARENTS = PARENTS;\n' +
  'window.PARENT_BY_ID = Object.fromEntries(PARENTS.map(p => [p.id, p]));\n' +
  'window.PARENT_BY_VARIANT_ID = {};\n' +
  'for (const p of PARENTS) for (const v of p.variants) window.PARENT_BY_VARIANT_ID[v.id] = p;\n';

fs.writeFileSync('./_parents_clinica_v2.js', out, 'utf-8');
console.log('OK: ' + parents.length + ' parents / ' + totalVariants + ' variants');
console.log('Multi-variant (will be shown): ' + parents.filter(p => p.variants.length > 1).length);
console.log('Singles: ' + parents.filter(p => p.variants.length === 1).length);
