  {"name":"Ariel","kana":"アリエール","letter":"A","hue":"#3E5A45","blurb":"P&G · laundry","items":54,"kind":"daily","name_ja":"アリエール","name_zh":"Ariel 碧浪"},
  {"name":"Bold","kana":"ボールド","letter":"B","hue":"#5B8C7F","blurb":"P&G · laundry","items":73,"kind":"daily","name_ja":"ボールド","name_zh":"Bold 博尔德"},
  {"name":"Sarasa","kana":"さらさ","letter":"S","hue":"#4A7C59","blurb":"P&G · laundry","items":10,"kind":"daily","name_ja":"さらさ","name_zh":"Sarasa 莎拉萨"},
  {"name":"Lenor","kana":"レノア","letter":"L","hue":"#BE9B4A","blurb":"P&G · fabric softener","items":160,"kind":"daily","name_ja":"レノア","name_zh":"Lenor 柔顺剂"},
  {"name":"Joy","kana":"ジョイ","letter":"J","hue":"#C2603F","blurb":"P&G · laundry","items":78,"kind":"daily","name_ja":"ジョイ","name_zh":"Joy 喜悦"},
  {"name":"Febreze","kana":"ファブリーズ","letter":"F","hue":"#9C6B3B","blurb":"P&G · deodorizer","items":224,"kind":"daily","name_ja":"ファブリーズ","name_zh":"Febreze 风倍清"},
  {"name":"Pantene","kana":"パンテーン","letter":"P","hue":"#9C6B3B","blurb":"P&G · haircare","items":133,"kind":"beauty","name_ja":"パンテーン","name_zh":"Pantene 潘婷"},
  {"name":"H&E","kana":"HE","letter":"H","hue":"#BE5A38","blurb":"P&G · haircare","items":2,"kind":"beauty","name_ja":"HE","name_zh":"H&E"},
  {"name":"Head & Shoulders","kana":"h&s","letter":"H","hue":"#2F5A4F","blurb":"P&G · haircare","items":45,"kind":"beauty","name_ja":"h&s","name_zh":"Head & Shoulders 海飞丝"},
  {"name":"Head & Shoulders for Men","kana":"h&s men","letter":"H","hue":"#3A4A66","blurb":"P&G · haircare","items":34,"kind":"beauty","name_ja":"h&s men","name_zh":"Head & Shoulders for Men"},
  {"name":"Hair Recipe","kana":"ヘアレシピ","letter":"H","hue":"#BE9B4A","blurb":"P&G · haircare","items":9,"kind":"beauty","name_ja":"ヘアレシピ","name_zh":"Hair Recipe 食谱发膜"},
  {"name":"Pampers","kana":"パンパース","letter":"P","hue":"#4A7C59","blurb":"P&G · baby","items":74,"kind":"babykids","name_ja":"パンパース","name_zh":"Pampers 帮宝适"},
  {"name":"Whisper","kana":"ウィスパー","letter":"W","hue":"#BE5A38","blurb":"P&G · femcare","items":72,"kind":"beauty","name_ja":"ウィスパー","name_zh":"Whisper 护舒宝"},
  {"name":"Oral-B","kana":"オーラルB","letter":"O","hue":"#3A4A66","blurb":"P&G · oral","items":3,"kind":"health","name_ja":"オーラルB","name_zh":"Oral-B 欧乐B"},
