BRAND_SLUG = {
  'White&White':'whitewhite','Clinica':'clinica','Denter':'denter','Systema':'systema',
  'Dent Health':'denthealth','NONIO':'nonio','Lightee':'lightee','Zact':'zact','Between':'between',
  'LION Kids':'lionkids','LION e-Toothbrush':'lionetb','OCH-TUNE':'ochtune','Migacot':'migacot',
  'Dental Rinse':'dentalrinse','Soft in One':'softinone','Oct':'oct',
  'Kirei Kirei':'kireikirei','Hadakara':'hadakara','Ban':'ban','Top':'top','NANOX':'nanox',
  'Acron':'acron','Bright':'bright','Soflan':'soflan','Soflan Premium':'soflan_premium',
  'Soflan Aroma':'soflan_aroma','Style Guard':'styleguard','Elegard':'elegard','Rain Guard':'rainguard',
  'Mama Lemon':'mamalemon','Magica':'magica','LION':'lion','Look':'look',
  'Bathtub Cleanser':'bathtub','Toilet Cleanser':'toilet','Mamepika':'mamepika',
  'Kose Ouvi Blue':'kose_ouvi','Kose Make Keep':'kose_makekeep','Kose Sekkisei':'kose_sekkisei',
  'Kose Infinity':'kose_infinity','Kose Grace One':'kose_grace','Visee':'visee','Fasio':'fasio',
  'Kumano Beauty':'kumano_beauty','Kumano Vuea':'kumano_vuea','Seihaku':'seihaku','cyclea':'cyclea',
  'and honey':'andhoney','BOTANIST':'botanist','Salon Link':'salonlink','Fino':'fino',
  'Pixy':'pixy','DEVECICA':'devecica','Chacott':'chacott','The':'the',
}

SERIES_RULES = {
  'Clinica': [
    ('_AD_brush_supercompact', r'クリニカＡＤ.*超コンパクト', 'brush', 'brush'),
    ('_AD_brush_compact', r'クリニカＡＤ.*コンパクト', 'brush', 'brush'),
    ('_AD_brush_regular', r'クリニカＡＤ.*レギュラー', 'brush', 'brush'),
    ('_AD_brush_other', r'クリニカＡＤ.*ハブラシ', 'brush', 'brush'),
    ('_AD_tauft', r'クリニカＡＤ.*デンタルタフト', 'accessory', 'tauft'),
    ('_AD_floss', r'クリニカＡＤ.*(デンタルフロス|フロス|スポンジ|ダブル)', 'accessory', 'floss'),
    ('_AD_rinse', r'クリニカＡＤ.*デンタルリンス', 'rinse', 'rinse'),
    ('_AD_gel', r'クリニカＡＤ.*ジェル', 'paste', 'gel'),
    ('_AD_paste', r'クリニカＡＤ', 'paste', 'paste'),
    ('_PRO_brush_rubber', r'クリニカＰＲＯ.*ラバーヘッド', 'brush', 'brush'),
    ('_PRO_brush_alarm', r'クリニカＰＲＯ.*アラームハンドル', 'brush', 'brush'),
    ('_PRO_brush_other', r'クリニカＰＲＯ.*ハブラシ', 'brush', 'brush'),
    ('_PRO_plus', r'クリニカＰＲＯ.*(プラス|歯周バリア)', 'paste', 'paste'),
    ('_PRO_white', r'クリニカＰＲＯ[ＷW]', 'paste', 'paste'),
    ('_PRO_allinone', r'クリニカＰＲＯ.*オールインワン', 'paste', 'paste'),
    ('_PRO_other', r'クリニカＰＲＯ', 'paste', 'paste'),
    ('_enamelpearl', r'エナメルパール', 'paste', 'paste'),
    ('_kids_brush', r'クリニカＫｉｄ.*ハブラシ|クリニカKid.*ハブラシ', 'brush', 'brush'),
    ('_kids_gel', r'クリニカＫｉｄ.*(ジェル|ジエル)|クリニカKid.*ジエル', 'paste', 'gel'),
    ('_kids_paste', r'クリニカＫｉｄ.*ハミガキ|クリニカKid.*ハミガキ', 'paste', 'paste'),
    ('_kids_rinse', r'クリニカＫｉｄ.*デンタルリンス|クリニカKid.*デンタルリンス', 'rinse', 'rinse'),
    ('_jr_paste', r'クリニカＪｒ.*ハミガキ|クリニカJr.*ハミガキ', 'paste', 'paste'),
    ('_jr_rinse', r'クリニカＪｒ.*デンタルリンス|クリニカJr.*デンタルリンス', 'rinse', 'rinse'),
    ('_jr', r'クリニカＪｒ|クリニカJr', 'paste', 'paste'),
    ('_migacot', r'ＭＩＧＡＣＯＴ|MIGACOT', 'set', 'set'),
    ('_fluor', r'フッ素メディカル', 'paste', 'coating'),
    ('_travel', r'トラベル', 'set', 'set'),
    ('_quickwash', r'クイックウォッシュ', 'rinse', 'rinse'),
    ('_standard', r'クリニカハミガキ', 'paste', 'paste'),
  ],
  'Systema': [
    ('_ex_rinse', r'システマＥＸ.*デンタルリンス', 'rinse', 'rinse'),
    ('_ex_brush', r'システマＥＸ.*ハブラシ', 'brush', 'brush'),
    ('_ex', r'システマＥＸ', 'paste', 'paste'),
    ('_pro_brush', r'システマＰＲＯ.*ハブラシ', 'brush', 'brush'),
    ('_pro', r'システマＰＲＯ', 'paste', 'paste'),
    # Brushes
    ('_hagukiplus_brush', r'システマハグキプラス.*ハブラシ', 'brush', 'brush'),
    ('_premium_brush', r'システマ.*極上プレミアム', 'brush', 'brush'),
    ('_shikkari_brush', r'システマ.*しっかり毛腰', 'brush', 'brush'),
    ('_compact_brush', r'システマ.*コンパクト', 'brush', 'brush'),
    ('_straight_brush', r'システマ.*ストレート', 'brush', 'brush'),
    ('_regular_brush', r'システマ.*レギュラー', 'brush', 'brush'),
    ('_supercompact_brush', r'システマ.*超コンパクト', 'brush', 'brush'),
    ('_tuft_brush', r'システマ.*デンタルタフト', 'brush', 'brush'),
    ('_handy_set', r'システマハンディ', 'set', 'set'),
    ('_interdental_brush', r'システマ.*歯間用ブラシ', 'brush', 'interdental'),
    ('_interdental_gel', r'システマ.*薬用歯間', 'paste', 'gel'),
    # Paste
    ('_hagukiplus_paste', r'システマハグキプラス', 'paste', 'paste'),
    ('_denter_standard', r'デンターシステマ', 'paste', 'paste'),
    ('_lion_etb_replace', r'電動アシストブラシ.*付替', 'brush', 'replace'),
    ('_standard', r'システマ', 'paste', 'paste'),
  ],
  'NONIO': [
    ('_mouthwash', r'マウスウォッシュ|デンタルリンス|リンス|ウォッシュ', 'rinse', 'rinse'),
    ('_gel', r'ジェル|ジエル', 'paste', 'gel'),
    ('_tongue', r'舌専用|舌クリ', 'paste', 'gel'),
    ('_paste', r'ＮＯＮＩＯハミガキ|ハミガキ', 'paste', 'paste'),
  ],
  'Lightee': [('_paste', r'Lighteeハミガキ|Ｌｉｇｈｔｅｅ', 'paste', 'paste')],
  'Denter': [('_standard', r'デンター', 'paste', 'paste')],
  'Dent Health': [('_standard', r'デントヘルス', 'paste', 'paste')],
  'Zact': [('_standard', r'ザクト', 'paste', 'paste')],
  'Between': [
    ('_regular', r'ビトイーンレギュラー', 'brush', 'brush'),
    ('_compact', r'ビトイーンコンパクト', 'brush', 'brush'),
    ('_standard', r'ビトイーン', 'brush', 'brush'),
  ],
  'LION Kids': [('_standard', r'ライオンこども', 'brush', 'brush')],
  'LION e-Toothbrush': [
    ('_main', r'電動アシストブラシ.*本体', 'main', 'main'),
    ('_replace', r'電動アシストブラシ.*付替', 'brush', 'replace'),
  ],
  'OCH-TUNE': [
    ('_mouthwash', r'マウスウォッシュ', 'rinse', 'rinse'),
    ('_brush', r'ハブラシ', 'brush', 'brush'),
  ],
  'Migacot': [('_case', r'ケース', 'accessory', 'case')],
  'Dental Rinse': [('_standard', r'デンタルリンス', 'rinse', 'rinse')],
  'Soft in One': [('_standard', r'ソフトインワン', 'rinse', 'rinse')],
  'Oct': [
    ('_serapie', r'ｓｅｒａｐｉｅ|serapie', 'shampoo', 'serapie'),
    ('_standard', r'オクト', 'shampoo', 'standard'),
  ],
  'Kirei Kirei': [
    ('_wipes', r'ウエットシート|おてふき|お手ふき', 'wipes', 'sheet'),
    ('_liquid_refill', r'詰替', 'handsoap', 'liquid'),
    ('_liquid_main', r'薬用液体ハンドソープ|薬用液体|薬用|液体ハンド', 'handsoap', 'liquid'),
    ('_foam', r'泡フォーム|ハンドフォーム|泡ハンド|フォーム', 'handsoap', 'foam'),
  ],
  'Hadakara': [
    ('_body_foam', r'ボディケアソープ 泡|ボディケア 泡', 'bodysoap', 'foam'),
    ('_body_liquid', r'ボディケア.*液体', 'bodysoap', 'liquid'),
    ('_body_main', r'モイストボディケアソープ|ボディケアソープ', 'bodysoap', 'liquid'),
    ('_bath', r'入浴|ボディウォッシュ', 'bodysoap', 'liquid'),
  ],
  'Ban': [
    ('_sheet', r'シート', 'wipes', 'sheet'),
    ('_powder', r'パウダー', 'deodorant', 'powder'),
  ],
  'Top': [
    ('_antibac', r'除菌|抗菌|クリーンリキッド', 'laundry', 'liquid'),
    ('_dry', r'部屋干し', 'laundry', 'liquid'),
    ('_lintfree', r'無リン', 'laundry', 'powder'),
    ('_standard', r'トップ|Top', 'laundry', 'liquid'),
  ],
  'NANOX': [
    ('_auto', r'自動投入', 'laundry', 'auto'),
    ('_one_pro', r'one.*Pro|one Pro|one ＰＲＯ', 'laundry', 'pouch'),
    ('_one_main', r'NANOX one|NANOX ＯＮＥ', 'laundry', 'liquid'),
    ('_standard', r'NANOX', 'laundry', 'liquid'),
  ],
  'Acron': [('_standard', r'アクロン', 'softener', 'liquid')],
  'Bright': [('_standard', r'ブライト|Bright', 'bleach', 'gel')],
  'Soflan': [
    ('_premium_deo', r'プレミアム|Ｐｒｅｍｉｕｍ', 'softener', 'liquid'),
    ('_standard', r'ソフラン', 'softener', 'liquid'),
  ],
  'Soflan Premium': [('_standard', r'プレミアム|ソフラン', 'softener', 'liquid')],
  'Soflan Aroma': [('_standard', r'アロマリッチ|ソフラン', 'softener', 'liquid')],
  'Style Guard': [('_standard', r'スタイルガード', 'fabric_care', 'spray')],
  'Elegard': [('_standard', r'エレガード', 'waterproof', 'spray')],
  'Rain Guard': [('_standard', r'レインガード', 'waterproof', 'spray')],
  'Mama Lemon': [('_standard', r'ママレモン', 'dishsoap', 'liquid')],
  'Magica': [('_standard', r'CHARMY Magica|Ｍａｇｉｃａ', 'dishsoap', 'liquid')],
  'LION': [
    ('_crista', r'クリスタ', 'dishsoap', 'gel'),
    ('_standard', r'CHARMY|ＬＩＯＮ', 'dishsoap', 'liquid'),
  ],
  'Look': [
    ('_plus', r'ルックプラス|Look Plus', 'cleaner', 'powder'),
    ('_standard', r'おふろのルック|ルック', 'cleaner', 'liquid'),
  ],
  'Bathtub Cleanser': [('_standard', r'バスタブクレンジング', 'cleaner', 'liquid')],
  'Toilet Cleanser': [('_standard', r'トイレクレンジング', 'cleaner', 'liquid')],
  'Mamepika': [
    ('_antibac', r'抗菌', 'cleaner', 'liquid'),
    ('_standard', r'まめピカ', 'cleaner', 'liquid'),
  ],
  'Kose Ouvi Blue': [
    ('_lotion', r'ローション|リンクレス', 'skincare', 'lotion'),
    ('_emulsion', r'エマルジョン|ＥＭ', 'skincare', 'emulsion'),
    ('_standard', r'ＯＢＫ|OBK', 'skincare', 'lotion'),
  ],
  'Kose Make Keep': [
    ('_powder', r'パウダー|パウダ', 'makeup', 'powder'),
    ('_primer', r'プライマー', 'makeup', 'primer'),
    ('_standard', r'メイクキープ|メイク キープ', 'makeup', 'powder'),
  ],
  'Kose Sekkisei': [
    ('_lotion', r'ケショウスイ|化粧水|エッセンス|乳液', 'skincare', 'lotion'),
    ('_mask', r'マスク', 'skincare', 'mask'),
    ('_standard', r'セッキセイ|雪肌精', 'skincare', 'lotion'),
  ],
  'Kose Infinity': [
    ('_foundation', r'ファンデーション|ベース|プレステディアス', 'makeup', 'foundation'),
    ('_mask', r'マスク|フェイスマスク', 'skincare', 'mask'),
    ('_gel', r'ジェル|ジエル', 'skincare', 'gel'),
    ('_milk', r'ミルク|エマルジョン|乳液', 'skincare', 'milk'),
    ('_lotion', r'アストリンゼント|化粧水|ローション', 'skincare', 'lotion'),
  ],
  'Kose Grace One': [
    ('_gel', r'ジェル|ジエル', 'skincare', 'gel'),
    ('_cream', r'クリーム', 'skincare', 'cream'),
    ('_essence', r'エッセンス|セラム|ＥＳ', 'skincare', 'serum'),
    ('_standard', r'グレイス ワン|Grace One', 'skincare', 'cream'),
  ],
  'Visee': [
    ('_eye_4color', r'ニュアンス デューイ|ニュアンス', 'makeup', 'eye'),
    ('_eye_liner', r'アイライナー|ライナー', 'makeup', 'eye'),
    ('_eye_mascara', r'マスカラ', 'makeup', 'eye'),
    ('_eye_brow', r'アイブロウ|ブロウ', 'makeup', 'eye'),
    ('_lip', r'リップ|口紅', 'makeup', 'lip'),
    ('_face', r'フェイス|チーク|ブラッシュ', 'makeup', 'face'),
  ],
  'Fasio': [
    ('_face', r'フェイスカラー|フェイスパウダー|ベース|コンシーラー|カバー|チーク|ブラッシュ|クッション|リキッド|キープ|マルチパーフェクション', 'makeup', 'face'),
    ('_eye_brow', r'アイブロウ|ブロウ', 'makeup', 'eye'),
    ('_eye_liner', r'アイライナー|ライナー|ダブル', 'makeup', 'eye'),
    ('_eye_mascara', r'マスカラ', 'makeup', 'eye'),
    ('_lip', r'リップ|ティント|口紅', 'makeup', 'lip'),
  ],
  'Kumano Beauty': [('_standard', r'熊野油脂|ビューア|麗白', 'skincare', 'lotion')],
  'Kumano Vuea': [('_refill', r'詰替', 'haircare', 'liquid')],
  'Seihaku': [
    ('_lotion', r'化粧水|ローション|みず|ミスト', 'skincare', 'lotion'),
    ('_milk', r'ボディミルク|ボディローション|乳液', 'skincare', 'milk'),
    ('_gel', r'ジェル|ジエル|マッサージ', 'skincare', 'gel'),
    ('_cream', r'クリーム', 'skincare', 'cream'),
    ('_uv', r'ＵＶ|UV|日焼け止め|ミルキー', 'skincare', 'uv'),
    ('_foam', r'洗顔|フォーム|ボディソープ|ソープ', 'skincare', 'foam'),
    ('_standard', r'麗白', 'skincare', 'lotion'),
  ],
  'cyclea': [
    ('_lotion', r'化粧水|ローション', 'skincare', 'lotion'),
    ('_milk', r'乳液|ミルク', 'skincare', 'milk'),
    ('_gel', r'ジェル|ジエル|ハイドロ', 'skincare', 'gel'),
    ('_uv', r'ＵＶ|UV|エッセンス', 'skincare', 'uv'),
    ('_soap', r'ボディソープ', 'skincare', 'soap'),
    ('_standard', r'cyclear|サイクルア', 'skincare', 'lotion'),
  ],
  'and honey': [
    ('_shampoo', r'シャンプー|Shampoo', 'haircare', 'shampoo'),
    ('_treatment', r'トリート|コン|Treatment', 'haircare', 'treatment'),
    ('_oil', r'オイル|Hair Oil', 'haircare', 'oil'),
    ('_mist', r'ミスト', 'haircare', 'mist'),
  ],
  'BOTANIST': [
    ('_shampoo', r'シャンプー|シャン', 'haircare', 'shampoo'),
    ('_treatment', r'トリート|トリー', 'haircare', 'treatment'),
    ('_oil', r'オイル|ヘアミスト|ヘアパック|ボディソープ|ヘアフォーム', 'haircare', 'oil'),
  ],
  'Salon Link': [
    ('_shampoo', r'シャンプー|シャン', 'haircare', 'shampoo'),
    ('_treatment', r'トリート|コン|コンディショナー', 'haircare', 'treatment'),
  ],
  'Fino': [
    ('_shampoo', r'シャンプー', 'haircare', 'shampoo'),
    ('_treatment', r'トリート|コン|コンディショナー', 'haircare', 'treatment'),
  ],
  'Pixy': [
    ('_pack', r'パック', 'haircare', 'pack'),
    ('_oil', r'オイル', 'haircare', 'oil'),
  ],
  'DEVECICA': [
    ('_shampoo', r'シャンプー|シャン', 'haircare', 'shampoo'),
    ('_treatment', r'トリート|コン|コンディショナー', 'haircare', 'treatment'),
    ('_bodysoap', r'オイル|ボディソープ|クレン|石鹸|バスアイテム|ウォッシュ', 'bodycare', 'liquid'),
  ],
  'Chacott': [
    ('_face', r'洗顔|フォーム|クレン|石鹸', 'facecare', 'foam'),
    ('_oil', r'オイル|クレンジング', 'facecare', 'oil'),
  ],
  'The': [
    ('_shampoo', r'シャンプー', 'haircare', 'shampoo'),
    ('_treatment', r'トリート', 'haircare', 'treatment'),
  ],
  'White&White': [('_standard', r'ホワイト＆ホワイト|White&White|Ｗｈｉｔｅ', 'oral', 'tube')],
}
